// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1bXPMtUwpXodiDT6G9KvNgk45Gmami4E',
    appId: '1:1003473576371:android:f97a0ee213529bc5792bc6',
    messagingSenderId: '1003473576371',
    projectId: 'keep-notes-adb09',
    storageBucket: 'keep-notes-adb09.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzHsDphbV2-zXZXez7kicNymgLfd_osU0',
    appId: '1:1003473576371:web:d178843a5d5a728b792bc6',
    messagingSenderId: '1003473576371',
    projectId: 'keep-notes-adb09',
    authDomain: 'keep-notes-adb09.firebaseapp.com',
    storageBucket: 'keep-notes-adb09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWdfheDx5ICJoxIp1aRCyDOiujNieoS1M',
    appId: '1:1003473576371:ios:3062e96a059628b3792bc6',
    messagingSenderId: '1003473576371',
    projectId: 'keep-notes-adb09',
    storageBucket: 'keep-notes-adb09.firebasestorage.app',
    androidClientId: '1003473576371-3isu8174agjo0pogcoi3bj86la1ho3cf.apps.googleusercontent.com',
    iosClientId: '1003473576371-hoc0cko4854si736itv0nholfl7qgk8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.keepNotes',
  );
}
