name: Flutter Web CI/CD

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Analyze, Test and Build Web
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v6

      # 2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      # 3. Show Flutter version
      - name: Flutter version
        run: flutter --version

      # 4. Enable Flutter Web
      - name: Enable Flutter Web
        run: flutter config --enable-web

      # 5. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 6. Analyze Dart code
      - name: Analyze
        run: flutter analyze

      # 7. Run tests
      - name: Test
        run: flutter test

      # 8. Build Flutter Web
      - name: Build Flutter Web
        run: flutter build web --release

      # 9. Upload Web Build
      - name: Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: keep-notes-web
          path: build/web


  deploy:
    name: Deploy Web to Firebase Hosting
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v6

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      # 3. Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 4. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      # 5. Enable Flutter Web
      - name: Enable Flutter Web
        run: flutter config --enable-web

      # 6. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 7. Build Flutter Web
      - name: Build Flutter Web
        run: flutter build web --release

      # 8. Deploy to Firebase Hosting
      - name: Deploy to Firebase
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}