name: Flutter Web CI/CD

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Analyze, Test & Build Web
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v6

      # 2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      # 3. Show Flutter version
      - name: Flutter version
        run: flutter --version

      # 4. Enable Flutter Web
      - name: Enable Flutter Web
        run: flutter config --enable-web

      # 5. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 6. Analyze Dart code
      - name: Analyze
        run: flutter analyze

      # 7. Run tests
      - name: Test
        run: flutter test

      # 8. Build Flutter Web
      - name: Build Flutter Web
        run: flutter build web --release

      # 9. Upload the exact build for deployment
      - name: Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: keep-notes-web
          path: build/web
          if-no-files-found: error
          retention-days: 7


  deploy:
    name: Deploy Web to Firebase Hosting
    needs: test

    # Deploy ONLY after a successful push to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v6

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      # 3. Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 4. Download the tested Web build
      - name: Download Web Build
        uses: actions/download-artifact@v5
        with:
          name: keep-notes-web
          path: build/web

      # 5. Deploy to Firebase Hosting
      - name: Deploy to Firebase
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}